#!/usr/bin/env python3
"""
Train a fastText intent classifier on labeled training data.

Input: training_data.jsonl (generated by extract-intent-training-data.ts)
       Each line: {"query": "...", "kind": "brand", "brand": "...", ...}

Output: model.bin — fastText model for intent classification

Usage:
  python3 python-intent/train.py
  python3 python-intent/train.py --source training_data.jsonl --output model.bin
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

DIR = Path(__file__).parent
sys.path.insert(0, str(DIR.parent))


def load_data(jsonl_path: str) -> list[tuple[str, str]]:
    """Load labeled data from JSONL. Returns list of (query, label)."""
    data: list[tuple[str, str]] = []
    with open(jsonl_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            query = obj.get("query", "").strip()
            label = obj.get("kind") or obj.get("label", "")
            if query and label:
                # fastText format: __label__className text
                data.append((f"__label__{label}", query))
    return data


def save_fasttext_format(data: list[tuple[str, str]], output: str) -> None:
    """Save data in fastText format (one line per example)."""
    with open(output, "w") as f:
        for label, text in data:
            f.write(f"{label} {text}\n")


def main():
    parser = argparse.ArgumentParser(description="Train fastText intent classifier")
    parser.add_argument(
        "--source",
        default=str(DIR / "training_data.jsonl"),
        help="Path to training data JSONL",
    )
    parser.add_argument(
        "--output",
        default=str(DIR / "model.bin"),
        help="Path for output model",
    )
    parser.add_argument(
        "--no-train",
        action="store_true",
        help="Only convert to fastText format, don't train",
    )
    args = parser.parse_args()

    # Load and convert data
    data = load_data(args.source)
    if not data:
        print(f"ERROR: No training data found in {args.source}", file=sys.stderr)
        print("Run: pnpm intent:extract-training -- --limit=100", file=sys.stderr)
        sys.exit(1)

    labels = set(label for label, _ in data)
    print(f"Loaded {len(data)} examples, {len(labels)} classes: {sorted(labels)}")

    # Save fastText format
    ft_file = str(Path(args.output).with_suffix(".txt"))
    save_fasttext_format(data, ft_file)

    if args.no_train:
        print(f"fastText training data saved to {ft_file}")
        return

    # Train fastText
    try:
        import fasttext
    except ImportError:
        print("fasttext not installed. Install with: pip install fasttext", file=sys.stderr)
        print(f"Training data saved to {ft_file}. Train manually.", file=sys.stderr)
        sys.exit(1)

    model = fasttext.train_supervised(
        input=ft_file,
        lr=0.5,
        epoch=25,
        wordNgrams=3,
        dim=100,
        loss="softmax",
        thread=os.cpu_count() or 4,
    )

    model.save_model(args.output)
    print(f"\nModel saved to {args.output}")

    # Test on training data (quick sanity check)
    results = model.test(ft_file)
    print(f"Training accuracy: {results[1] * 100:.1f}%")
    print(f"Precision: {results[0]} (samples: {results[2]})")


if __name__ == "__main__":
    main()
