/* AUTO-GENERATED by scripts/sync-lottie.ts — do not edit by hand.
 * Source: ~/Downloads/scout-cats/  (drop .lottie/.json files there and re-run `pnpm cats:sync`).
 * Cross-mode (fly across the screen) is configured per-file in cats.config.json.
 */
export type LottieAsset = { src: string; cross?: "rtl" | "ltr" };
export const LOTTIE_ASSETS: LottieAsset[] = [
  {
    "src": "cat.lottie"
  },
  {
    "src": "comp-a.lottie",
    "cross": "ltr"
  },
  {
    "src": "comp-b.lottie"
  },
  {
    "src": "ghibli.lottie",
    "cross": "rtl"
  },
  {
    "src": "meow.lottie"
  },
  {
    "src": "no-connection.lottie"
  },
  {
    "src": "preloader-cat.json"
  },
  {
    "src": "pumpkin.lottie"
  },
  {
    "src": "witch.lottie"
  }
];
