#!/usr/bin/env -S pnpm tsx
/**
 * Build the search taxonomy manifest from the live index's Zepto hierarchy.
 *
 *   pnpm search:build-taxonomy
 *
 * Emits lib/search/v2/taxonomy.generated.ts:
 *   - TAXONOMY: category → ranked subcategories (the controlled vocabulary the
 *     query→category resolver classifies into)
 *   - CATEGORIES / SUBCATEGORIES: flat lists
 *   - SUBCATEGORY_TO_CATEGORY: subcategory → parent category
 *   - TYPE_TO_FACET: freeform primary_type → its dominant {category, subcategory}
 *     so fast-path (non-LLM) queries still ground on the clean hierarchy.
 *
 * Re-run whenever the catalog/taxonomy shifts (cheap, read-only).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { config as loadEnv } from "dotenv";

loadEnv({ path: ".env.local" });

async function main() {
  const url = process.env.SUPABASE_DB_URL ?? process.env.DATABASE_URL;
  if (!url) {
    console.error("[taxonomy] Missing SUPABASE_DB_URL in .env.local");
    process.exit(1);
  }
  const { default: postgres } = await import("postgres");
  const sql = postgres(url, { max: 1 });
  try {
    // category → subcategory counts (build the tree, subcats ranked by size)
    const tree = await sql<{ category: string; subcategory: string; n: number }[]>`
      SELECT category, subcategory, count(*)::int n
      FROM product_search_index
      WHERE category IS NOT NULL AND category <> '' AND subcategory IS NOT NULL AND subcategory <> ''
      GROUP BY category, subcategory
      ORDER BY category, n DESC`;

    const TAXONOMY: Record<string, string[]> = {};
    const SUBCATEGORY_TO_CATEGORY: Record<string, string> = {};
    for (const r of tree) {
      (TAXONOMY[r.category] ??= []).push(r.subcategory);
      // first (largest) parent wins if a subcategory name recurs across categories
      if (!(r.subcategory in SUBCATEGORY_TO_CATEGORY)) {
        SUBCATEGORY_TO_CATEGORY[r.subcategory] = r.category;
      }
    }
    const CATEGORIES = Object.keys(TAXONOMY).sort();
    const SUBCATEGORIES = Object.keys(SUBCATEGORY_TO_CATEGORY).sort();

    // primary_type → dominant {category, subcategory}
    const typeRows = await sql<
      { primary_type: string; category: string; subcategory: string; n: number }[]
    >`
      SELECT primary_type, category, subcategory, count(*)::int n
      FROM product_search_index
      WHERE primary_type IS NOT NULL AND primary_type <> '' AND category IS NOT NULL AND subcategory IS NOT NULL
      GROUP BY primary_type, category, subcategory`;
    // Per primary_type: the dominant (category, subcategory) PLUS how CONCENTRATED
    // the type is in that dominant subcategory / category. Umbrella types ("snacks",
    // "drinks") are spread thin across many subcategories, so their single dominant
    // facet is an unreliable grounding signal — the resolver uses these ratios to
    // ground only confident types (subcategory when concentrated, else category,
    // else not at all). Concentrated types ("pickle", "milk") ground tightly.
    const best = new Map<string, { category: string; subcategory: string; n: number }>();
    const totalByType = new Map<string, number>();
    const catCount = new Map<string, Map<string, number>>();
    for (const r of typeRows) {
      const k = r.primary_type.toLowerCase().trim();
      totalByType.set(k, (totalByType.get(k) ?? 0) + r.n);
      const cm = catCount.get(k) ?? new Map<string, number>();
      cm.set(r.category, (cm.get(r.category) ?? 0) + r.n);
      catCount.set(k, cm);
      const cur = best.get(k);
      if (!cur || r.n > cur.n) best.set(k, { category: r.category, subcategory: r.subcategory, n: r.n });
    }
    const round2 = (x: number) => Math.round(x * 100) / 100;
    const TYPE_TO_FACET: Record<
      string,
      { category: string; subcategory: string; subConc: number; catConc: number }
    > = {};
    for (const [k, v] of [...best.entries()].sort()) {
      const total = totalByType.get(k) ?? v.n;
      const maxCat = Math.max(...[...(catCount.get(k)?.values() ?? [v.n])]);
      TYPE_TO_FACET[k] = {
        category: v.category,
        subcategory: v.subcategory,
        subConc: round2(v.n / total),
        catConc: round2(maxCat / total),
      };
    }

    const banner = `// AUTO-GENERATED by scripts/build-taxonomy.ts — do not edit by hand.\n// Source: product_search_index Zepto hierarchy. Re-run: pnpm search:build-taxonomy\n`;
    const body =
      banner +
      `\nexport const CATEGORIES: string[] = ${JSON.stringify(CATEGORIES, null, 2)};\n` +
      `\nexport const TAXONOMY: Record<string, string[]> = ${JSON.stringify(TAXONOMY, null, 2)};\n` +
      `\nexport const SUBCATEGORY_TO_CATEGORY: Record<string, string> = ${JSON.stringify(SUBCATEGORY_TO_CATEGORY, null, 2)};\n` +
      `\nexport const SUBCATEGORIES: string[] = ${JSON.stringify(SUBCATEGORIES, null, 2)};\n` +
      `\nexport const TYPE_TO_FACET: Record<string, { category: string; subcategory: string; subConc: number; catConc: number }> = ${JSON.stringify(TYPE_TO_FACET, null, 2)};\n`;

    const out = join(process.cwd(), "lib/search/v2/taxonomy.generated.ts");
    writeFileSync(out, body);
    console.log(
      `[taxonomy] wrote ${out}\n  categories=${CATEGORIES.length} subcategories=${SUBCATEGORIES.length} type_map=${Object.keys(TYPE_TO_FACET).length}`,
    );
  } finally {
    await sql.end({ timeout: 8 });
  }
}

main().catch((e) => {
  console.error("[taxonomy] FAILED:", e);
  process.exit(1);
});
