#!/usr/bin/env -S pnpm tsx
/**
 * Re-classify ingredient_intelligence rows that were generated by local Qwen/LM Studio models.
 *
 * Problems with Qwen-generated rows:
 *   1. Many "problematic" entries are legitimate ingredients (e.g. "peanut")
 *   2. ~100+ entries have malformed normalized_name (OCR artifacts with brackets/parens)
 *   3. concern_reasons are often generic/unsourced ("cancer risk", "ultra-processed additive")
 *
 * This script:
 *   1. Finds all rows where model contains "qwen" or "lm_studio"
 *   2. Skips malformed normalized_names (contain [ ] ( ) etc.)
 *   3. Re-classifies using DeepSeek V4 Flash
 *   4. Updates rows with better tier + reasons + model tag
 *   5. Deletes rows with malformed names (they shouldn't exist)
 *
 *   pnpm tsx scripts/reclassify-ingredient-intelligence.ts -- --dry-run
 *   pnpm tsx scripts/reclassify-ingredient-intelligence.ts -- --limit=50
 *   pnpm tsx scripts/reclassify-ingredient-intelligence.ts
 */

import { config as loadEnv } from "dotenv";
import { adminClient } from "@/lib/supabase/admin";
import { scriptArgv } from "@/lib/util/script-argv";

loadEnv({ path: ".env.local" });

const argv = scriptArgv();
const DRY_RUN = argv.includes("--dry-run");
const LIMIT = (() => {
  const a = argv.find((a) => a.startsWith("--limit="));
  return a ? Number(a.split("=")[1]) : 500;
})();
const CONCURRENCY = 5;
const BATCH_SIZE = 20;

const API_KEY = process.env.DEEPSEEK_API_KEY ?? "";
const MODEL = process.env.DEEPSEEK_MODEL ?? "deepseek-v4-flash";
const BASE_URL = (process.env.DEEPSEEK_BASE_URL ?? "https://api.deepseek.com/v1").replace(/\/+$/, "");

const CLASSIFY_SYSTEM = `You classify food ingredients used in Indian packaged foods.
Return exactly one JSON object, no markdown.

Schema:
{
  "concern_tier": "innocuous" | "limited" | "moderate" | "hazardous" | "unknown",
  "role": "base_food" | "fat" | "sugar" | "salt" | "preservative" | "colour" | "flavour" | "emulsifier" | "thickener" | "antioxidant" | "sweetener" | "raising_agent" | "acidulant" | "vitamin_mineral" | "probiotic" | "protein_source" | "fibre" | "other",
  "nova_class": 1 | 2 | 3 | 4,
  "concern_reasons": string[],
  "confidence": 0.0-1.0
}

Tiers:
- innocuous: safe whole foods, water, salt, basic spices, permitted additives with no real concern
- limited: some evidence of minor concern but generally recognised as safe (e.g. aspartame, palm oil)
- moderate: moderate scientific concern (e.g. BHA, tartrazine, trans fats, sodium nitrite)
- hazardous: strong scientific concern or banned in some countries (e.g. potassium bromate)
- unknown: can't classify with confidence

For Indian food context: peanuts, roasted peanuts, peanut butter = innocuous base_food NOVA 1.
INS/E numbers: classify by the actual additive class.`;

async function classifyIngredient(
  name: string,
): Promise<{
  concern_tier: string;
  role: string;
  nova_class: number;
  concern_reasons: string[];
  confidence: number;
} | null> {
  if (!API_KEY) return null;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 12_000);
  try {
    const res = await fetch(`${BASE_URL}/chat/completions`, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${API_KEY}` },
      body: JSON.stringify({
        model: MODEL,
        temperature: 0,
        max_tokens: 200,
        response_format: { type: "json_object" },
        thinking: { type: "disabled" },
        messages: [
          { role: "system", content: CLASSIFY_SYSTEM },
          { role: "user", content: `Classify this ingredient: "${name}"` },
        ],
      }),
      signal: controller.signal,
    });
    if (!res.ok) return null;
    const body = await res.json() as { choices?: Array<{ message?: { content?: string } }> };
    const content = body.choices?.[0]?.message?.content;
    if (!content) return null;
    const raw = JSON.parse(content) as {
      concern_tier?: string;
      role?: string;
      nova_class?: number;
      concern_reasons?: string[];
      confidence?: number;
    };
    return {
      concern_tier: raw.concern_tier ?? "unknown",
      role: raw.role ?? "other",
      nova_class: raw.nova_class ?? 4,
      concern_reasons: raw.concern_reasons ?? [],
      confidence: raw.confidence ?? 0.5,
    };
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

function isMalformed(name: string): boolean {
  // Names that are OCR/parsing artifacts, not real ingredient names
  return (
    name.startsWith(")") ||
    name.startsWith("]") ||
    name.startsWith("(") ||
    name.startsWith("[") ||
    /^\s*[)\]]+/.test(name) ||
    name.length > 120 || // absurdly long "names"
    /\binst\b|\binsulin\b/i.test(name) && !/\binstant\b/i.test(name) // "ins" being misread
  );
}

async function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

async function main() {
  const supabase = adminClient();

  console.log(`[reclassify] Fetching rows generated by local models...`);

  // Get all Qwen/LM Studio rows
  const { data: rows, error } = await supabase
    .from("ingredient_intelligence")
    .select("normalized_name, concern_tier, model, concern_reasons")
    .or("model.ilike.%qwen%,model.ilike.%lm_studio%,model.ilike.%lmstudio%")
    .limit(LIMIT);

  if (error) throw new Error(error.message);
  console.log(`Found ${rows?.length ?? 0} rows to review.`);

  const malformed = rows?.filter((r) => isMalformed(r.normalized_name)) ?? [];
  const toReclassify = rows?.filter((r) => !isMalformed(r.normalized_name)) ?? [];

  console.log(`  ${malformed.length} malformed (will delete)`);
  console.log(`  ${toReclassify.length} to reclassify with DeepSeek`);

  if (DRY_RUN) {
    console.log("\n[dry-run] Would delete malformed:");
    malformed.slice(0, 5).forEach((r) => console.log("  DEL:", r.normalized_name));
    console.log("\n[dry-run] Would reclassify:");
    toReclassify.slice(0, 5).forEach((r) => console.log("  RECLASSIFY:", r.normalized_name, "| current:", r.concern_tier));
    return;
  }

  // Delete malformed rows
  if (malformed.length > 0) {
    const names = malformed.map((r) => r.normalized_name);
    const { error: delError } = await supabase
      .from("ingredient_intelligence")
      .delete()
      .in("normalized_name", names);
    console.log(`Deleted ${malformed.length} malformed rows${delError ? ` (error: ${delError.message})` : " ✓"}`);
  }

  // Reclassify in batches
  let processed = 0;
  let updated = 0;
  let errors = 0;

  for (let i = 0; i < toReclassify.length; i += CONCURRENCY) {
    const batch = toReclassify.slice(i, i + CONCURRENCY);
    const results = await Promise.all(
      batch.map(async (row) => {
        const classification = await classifyIngredient(row.normalized_name);
        return { row, classification };
      })
    );

    const upserts = results
      .filter((r) => r.classification !== null)
      .map(({ row, classification }) => ({
        normalized_name: row.normalized_name,
        concern_tier: classification!.concern_tier,
        role: classification!.role,
        nova_class: classification!.nova_class,
        concern_reasons: classification!.concern_reasons,
        model: `deepseek_v4_flash_reclassify`,
        rated_at: new Date().toISOString(),
      }));

    if (upserts.length > 0) {
      const { error: upsertError } = await supabase
        .from("ingredient_intelligence")
        .upsert(upserts, { onConflict: "normalized_name" });
      if (upsertError) {
        console.error(`Upsert error: ${upsertError.message}`);
        errors++;
      } else {
        updated += upserts.length;
      }
    }

    processed += batch.length;
    errors += results.filter((r) => r.classification === null).length;

    if (processed % 50 === 0) {
      console.log(`[reclassify] ${processed}/${toReclassify.length} processed, ${updated} updated, ${errors} errors`);
    }

    // Small delay to avoid hammering the API
    if (i + CONCURRENCY < toReclassify.length) await sleep(200);
  }

  console.log(`\n[reclassify] Done: ${updated}/${toReclassify.length} reclassified, ${errors} errors`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
