#!/usr/bin/env -S pnpm tsx
/**
 * Copy Supabase + API URL from root .env.local into oasis-mobile/.env
 *   pnpm mobile:env
 *
 * Default: production Vercel API (works worldwide with `pnpm mobile:start` + Expo tunnel).
 * Local API on same Wi‑Fi only: set EXPO_PUBLIC_MOBILE_API_MODE=local in .env.local
 */
import { networkInterfaces } from "node:os";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT_ENV = resolve(process.cwd(), ".env.local");
const MOBILE_ENV = resolve(process.cwd(), "oasis-mobile/.env");
const PRODUCTION_API = "https://oasis-phi-one.vercel.app";

function parseEnv(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i < 0) continue;
    map.set(t.slice(0, i).trim(), t.slice(i + 1).trim());
  }
  return map;
}

function isLoopbackUrl(url: string): boolean {
  try {
    const host = new URL(url).hostname;
    return host === "localhost" || host === "127.0.0.1";
  } catch {
    return false;
  }
}

function isPrivateLanUrl(url: string): boolean {
  try {
    const host = new URL(url).hostname;
    return (
      /^192\.168\./.test(host) ||
      /^10\./.test(host) ||
      /^172\.(1[6-9]|2\d|3[01])\./.test(host)
    );
  } catch {
    return false;
  }
}

function pickLanIPv4(): string | null {
  const nets = networkInterfaces();
  for (const ifaces of Object.values(nets)) {
    for (const net of ifaces ?? []) {
      if (net.family === "IPv4" && !net.internal) return net.address;
    }
  }
  return null;
}

function resolveMobileApiUrl(vars: Map<string, string>): string {
  const mode = vars.get("EXPO_PUBLIC_MOBILE_API_MODE")?.toLowerCase();
  const explicit = vars.get("EXPO_PUBLIC_API_URL")?.replace(/\/+$/, "");

  if (mode === "local") {
    const lan = pickLanIPv4();
    if (lan) return `http://${lan}:3000`;
    console.warn("EXPO_PUBLIC_MOBILE_API_MODE=local but no LAN IP found — using production API.");
    return PRODUCTION_API;
  }

  // Worldwide Expo Go + tunnel: always use public HTTPS unless explicitly overridden.
  if (explicit && !isLoopbackUrl(explicit) && !isPrivateLanUrl(explicit)) {
    return explicit;
  }

  return PRODUCTION_API;
}

function main() {
  let root: string;
  try {
    root = readFileSync(ROOT_ENV, "utf8");
  } catch {
    console.error("Missing .env.local in repo root. Copy .env.local.example and fill values.");
    process.exit(1);
  }
  const vars = parseEnv(root);
  const apiUrl = resolveMobileApiUrl(vars);
  const supabaseUrl = vars.get("EXPO_PUBLIC_SUPABASE_URL") ?? vars.get("NEXT_PUBLIC_SUPABASE_URL");
  const anonKey =
    vars.get("EXPO_PUBLIC_SUPABASE_ANON_KEY") ?? vars.get("NEXT_PUBLIC_SUPABASE_ANON_KEY");

  if (!supabaseUrl || !anonKey) {
    console.error(".env.local must set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY");
    process.exit(1);
  }

  const out = `# Auto-generated by pnpm mobile:env — same Supabase project as web Scout
# Default: production API (share QR worldwide via pnpm mobile:start / expo --tunnel)
# Same-Wi‑Fi local API only: EXPO_PUBLIC_MOBILE_API_MODE=local in root .env.local

EXPO_PUBLIC_API_URL=${apiUrl}
EXPO_PUBLIC_MOBILE_API_MODE=${vars.get("EXPO_PUBLIC_MOBILE_API_MODE") ?? "production"}
EXPO_PUBLIC_SUPABASE_URL=${supabaseUrl}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
`;

  writeFileSync(MOBILE_ENV, out, "utf8");
  console.log(`Wrote ${MOBILE_ENV}`);
  console.log(`  API: ${apiUrl}`);
  console.log(`  Supabase: ${supabaseUrl}`);
  if (apiUrl.startsWith("http://")) {
    console.log("");
    console.log("  Local LAN API — phone must be on the same Wi‑Fi. For worldwide QR, run:");
    console.log("    pnpm mobile:env   (with EXPO_PUBLIC_MOBILE_API_MODE unset or production)");
    console.log("    pnpm mobile:start");
  } else {
    console.log("");
    console.log("  Share worldwide: pnpm mobile:start  (Expo tunnel + production API)");
  }
}

main();
