#!/usr/bin/env -S pnpm tsx
/**
 * Sync Lottie cat assets from ~/Downloads/scout-cats/ → public/lottie/ and
 * generate lib/lottie-manifest.ts so the component picks them up automatically.
 *
 *   pnpm cats:sync   # manual
 *   (also runs as predev / prebuild so it stays fresh)
 *
 * Source folder is the truth: drop a .lottie or .json file there, restart the
 * dev server, and it'll appear in the rotation. Mark animations that should fly
 * across the screen (vs loop in place) in cats.config.json inside the folder:
 *   { "kiki.lottie": { "cross": "rtl" } }
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const SRC = join(homedir(), "Downloads", "scout-cats");
const DEST = join(repo, "public", "lottie");
const MANIFEST = join(repo, "lib", "lottie-manifest.ts");
const CONFIG = join(SRC, "cats.config.json");

mkdirSync(DEST, { recursive: true });
mkdirSync(dirname(MANIFEST), { recursive: true });

type CrossDir = "rtl" | "ltr";
type Config = Record<string, { cross?: CrossDir }>;

// On Vercel/CI the source folder doesn't exist — leave public/lottie + the
// committed manifest exactly as they are. Locally, ~/Downloads/scout-cats/ is
// the source of truth: drop files there, run `pnpm cats:sync`, refresh.
if (!existsSync(SRC)) {
  console.log(`[sync-lottie] source ${SRC} missing — using committed public/lottie + manifest as-is.`);
  process.exit(0);
}

const config: Config = existsSync(CONFIG)
  ? (JSON.parse(readFileSync(CONFIG, "utf8")) as Config)
  : {};

const files = readdirSync(SRC)
  .filter((f) => /\.(lottie|json)$/i.test(f))
  .filter((f) => f !== "cats.config.json") // the config itself isn't a Lottie asset
  .sort();

let copied = 0;
for (const f of files) {
  copyFileSync(join(SRC, f), join(DEST, f));
  copied++;
}

type Asset = { src: string; cross?: CrossDir };
const assets: Asset[] = files.map((f) => {
  const cfg = config[f];
  return cfg?.cross ? { src: f, cross: cfg.cross } : { src: f };
});

const banner = `/* AUTO-GENERATED by scripts/sync-lottie.ts — do not edit by hand.
 * Source: ~/Downloads/scout-cats/  (drop .lottie/.json files there and re-run \`pnpm cats:sync\`).
 * Cross-mode (fly across the screen) is configured per-file in cats.config.json.
 */\n`;
const body = `export type LottieAsset = { src: string; cross?: "rtl" | "ltr" };\nexport const LOTTIE_ASSETS: LottieAsset[] = ${JSON.stringify(assets, null, 2)};\n`;
writeFileSync(MANIFEST, banner + body);

console.log(`[sync-lottie] ${copied} asset${copied === 1 ? "" : "s"} synced from ${SRC} → public/lottie/`);
console.log(`[sync-lottie] manifest: ${MANIFEST.replace(repo + "/", "")}  (${assets.filter((a) => a.cross).length} cross, ${assets.filter((a) => !a.cross).length} fixed)`);
