#!/usr/bin/env -S pnpm tsx
/**
 * Copy Supabase + API URL from root .env.local into oasis-mobile/.env
 *   pnpm mobile:env
 */
import { readFile, writeFile } from "node:fs";
import { resolve } from "node:path";

const ROOT_ENV = resolve(process.cwd(), ".env.local");
const MOBILE_ENV = resolve(process.cwd(), "oasis-mobile/.env");

function parseEnv(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i < 0) continue;
    map.set(t.slice(0, i).trim(), t.slice(i + 1).trim());
  }
  return map;
}

function main() {
  let root: string;
  try {
    root = readFile(ROOT_ENV, "utf8");
  } catch {
    console.error("Missing .env.local in repo root. Copy .env.local.example and fill values.");
    process.exit(1);
  }
  const vars = parseEnv(root);
  const apiUrl =
    vars.get("EXPO_PUBLIC_API_URL") ??
    vars.get("NEXT_PUBLIC_SITE_URL") ??
    "http://localhost:3000";
  const supabaseUrl = vars.get("EXPO_PUBLIC_SUPABASE_URL") ?? vars.get("NEXT_PUBLIC_SUPABASE_URL");
  const anonKey =
    vars.get("EXPO_PUBLIC_SUPABASE_ANON_KEY") ?? vars.get("NEXT_PUBLIC_SUPABASE_ANON_KEY");

  if (!supabaseUrl || !anonKey) {
    console.error(".env.local must set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY");
    process.exit(1);
  }

  const out = `# Auto-generated by pnpm mobile:env — same Supabase project as web Scout
# Re-run after changing root .env.local

EXPO_PUBLIC_API_URL=${apiUrl.replace(/\/+$/, "")}
EXPO_PUBLIC_SUPABASE_URL=${supabaseUrl}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
`;

  writeFile(MOBILE_ENV, out, "utf8");
  console.log(`Wrote ${MOBILE_ENV}`);
  console.log(`  API: ${apiUrl}`);
  console.log(`  Supabase: ${supabaseUrl}`);
}

main();
